### PR TITLE
feat: add support for typescript types-prefix opt

### PR DESCRIPTION
**Pull request by polRk**
Fix: #77, #76

### CODE REVIEW

**Comment by eddeee888** [comment]
Hi @polRk, thanks for the PR. 

Can you help me understand why you'd like this feature implemented please? :)

**Comment by polRk** [comment]
> Hi @polRk, thanks for the PR. 
> 
> 
> 
> Can you help me understand why you'd like this feature implemented please? :)

For typescript. Nothing works without the right types

**Comment by eddeee888** [comment]
Sorry, I should have been clearer here. 

What about the default interfaces/types naming does not work for you? 
Is the type prefix needed because of your code standard? e.g. all interfaces must have `I` prefix

I'm thinking to limit the options that can be passed in through `typesPluginsConfig` to keep the preset lean. Especially options around interfaces/types naming. `typesPrefix` is one of them.

**Comment by polRk** [comment]
> 

All our types use the prefix I. We have many identical by name entities and prefix generation is the only right option to solve typescripts issues

**Comment by eddeee888** [comment]
> All our types use the prefix I

Does this apply to just the generation types or all types in your project?

> We have many identical by name entities

One of the main goal of this project is to do all the heavy lifting with types so you don't have to do any manual imports. Do you find yourself needing to import from the generated types file?

**Comment by eddeee888** [comment]
This is now fixed in [v0.10](https://github.com/eddeee888/graphql-code-generator-plugins/releases/tag/%40eddeee888%2Fgcg-typescript-resolver-files%400.10.0)

**Pull request closed without merging**
